# My Card Game — STS-inspired Roguelike Deckbuilder card definitions
# See docs/GAME_DESIGN.md for full design spec
extends RefCounted

const SET = "My Card Game"
const CARDS := {
	# === Starting Deck (10 cards) ===
	"Strike": {
		"Type": "Attack",
		"Tags": ["Starter"],
		"Abilities": "造成 6 点伤害",
		"Cost": 1,
		"Damage": 6,
		"Block": 0,
		"_rarity": "Starter",
		"_effects": [],
	},
	"Defend": {
		"Type": "Skill",
		"Tags": ["Starter"],
		"Abilities": "获得 5 点格挡",
		"Cost": 1,
		"Damage": 0,
		"Block": 5,
		"_rarity": "Starter",
		"_effects": [],
	},
	"Bash": {
		"Type": "Attack",
		"Tags": ["Starter"],
		"Abilities": "造成 8 点伤害\n施加 2 层易伤",
		"Cost": 2,
		"Damage": 8,
		"Block": 0,
		"_rarity": "Starter",
		"_effects": ["vulnerable:2"],
	},
	# === Reward Pool (7 cards) ===
	"Cleave": {
		"Type": "Attack",
		"Tags": ["Common"],
		"Abilities": "造成 8 点伤害",
		"Cost": 1,
		"Damage": 8,
		"Block": 0,
		"_rarity": "Common",
		"_effects": [],
	},
	"Iron Wave": {
		"Type": "Attack",
		"Tags": ["Common"],
		"Abilities": "造成 5 点伤害\n获得 5 点格挡",
		"Cost": 1,
		"Damage": 5,
		"Block": 5,
		"_rarity": "Common",
		"_effects": [],
	},
	"Shrug It Off": {
		"Type": "Skill",
		"Tags": ["Common"],
		"Abilities": "获得 8 点格挡\n抽 1 张牌",
		"Cost": 1,
		"Damage": 0,
		"Block": 8,
		"_rarity": "Common",
		"_effects": ["draw:1"],
	},
	"Pommel Strike": {
		"Type": "Attack",
		"Tags": ["Common"],
		"Abilities": "造成 9 点伤害\n抽 1 张牌",
		"Cost": 1,
		"Damage": 9,
		"Block": 0,
		"_rarity": "Common",
		"_effects": ["draw:1"],
	},
	"Inflame": {
		"Type": "Power",
		"Tags": ["Uncommon"],
		"Abilities": "获得 2 点力量（永久）",
		"Cost": 1,
		"Damage": 0,
		"Block": 0,
		"_rarity": "Uncommon",
		"_effects": ["strength:2"],
	},
	"Bloodletting": {
		"Type": "Skill",
		"Tags": ["Uncommon"],
		"Abilities": "失去 3 HP\n获得 2 点能量",
		"Cost": 0,
		"Damage": 0,
		"Block": 0,
		"_rarity": "Uncommon",
		"_effects": ["lose_hp:3", "gain_energy:2"],
	},
	"Heavy Blow": {
		"Type": "Attack",
		"Tags": ["Rare"],
		"Abilities": "造成 14 点伤害\n（受力量加成）",
		"Cost": 2,
		"Damage": 14,
		"Block": 0,
		"_rarity": "Rare",
		"_effects": ["strength_scaling"],
	},
	"Poison Stab": {
		"Type": "Attack",
		"Tags": ["Common"],
		"Abilities": "造成 4 点伤害\n施加 3 层中毒",
		"Cost": 1,
		"Damage": 4,
		"Block": 0,
		"_rarity": "Common",
		"_effects": ["poison:3"],
	},
	"Crippling Blow": {
		"Type": "Attack",
		"Tags": ["Common"],
		"Abilities": "造成 9 点伤害\n施加 2 层虚弱",
		"Cost": 2,
		"Damage": 9,
		"Block": 0,
		"_rarity": "Common",
		"_effects": ["weak:2"],
	},
	"Bandage": {
		"Type": "Skill",
		"Tags": ["Uncommon"],
		"Abilities": "回复 6 HP",
		"Cost": 1,
		"Damage": 0,
		"Block": 0,
		"_rarity": "Uncommon",
		"_effects": ["heal:6"],
	},
	"Thorns": {
		"Type": "Skill",
		"Tags": ["Uncommon"],
		"Abilities": "获得 8 点格挡\n获得 3 点荆棘",
		"Cost": 1,
		"Damage": 0,
		"Block": 8,
		"_rarity": "Uncommon",
		"_effects": ["thorns:3"],
	},
	"Shield Bash": {
		"Type": "Attack",
		"Tags": ["Rare"],
		"Abilities": "造成等同于格挡值的伤害",
		"Cost": 2,
		"Damage": 0,
		"Block": 0,
		"_rarity": "Rare",
		"_effects": ["shield_bash"],
	},
	"Fiend Fire": {
		"Type": "Attack",
		"Tags": ["Rare"],
		"Abilities": "造成 15 点伤害\n施加 2 层中毒",
		"Cost": 2,
		"Damage": 15,
		"Block": 0,
		"_rarity": "Rare",
		"_effects": ["poison:2"],
	},
}
